portfolio/Joan/urls.py
from django .urls import path,include
from . import views

app_name = "Joan"
urlpatterns = [
    path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('languages/', views.languages, name='languages'),
path('services/', views.services, name='services'),
path('contacts/', views.contacts, name='contacts')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Joan.urls'))
]

portfolio/Joan/models.py
from django.db import models

# Create your models here.

portfolio/Joan/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')
def about(request):
    return render(request, 'about.html')
def contacts(request):
    return render(request, 'contacts.html')
def languages(request):
    return render(request, 'languages.html')
def services(request):
    return render(request, 'services.html')

portfolio/Joan/templates/about.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
    <section class="container mt-5">
    <h2 class="text-center mb-4">About Me</h2>

    <div class="row">

        <div class="col-md-4 mb-4">
            <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>

        <div class="col-md-8">
                        <p>My name is Ms Joan chebet,iam outgoing, dedicated, and open-minded. I get across to people and adjust to changes with ease. I believe that a person should work on developing their professional skills and learning new things all the time.</p>
        </div>
    </div>



</section>
{% endblock %}

portfolio/Joan/templates/contacts.html
{% extends 'layout.html' %}
{% block body %}


    <section class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Contact Information</h3>
            <ul class="list-unstyled">
                <li><strong>Phone:</strong> +254708242977</li>
                <li><strong>Email:</strong>chebetjoan110@gmail.com</li>
                <li><strong>Address:</strong> 811-20210</li>
            </ul>
        </div>


        <div class="row mt-5">

        <div class="col-md-6">
            <h3>Send a Message</h3>
            <form>
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                </div>
                <div class="row mt-5">
            <div class="col-12">
                <h3>Am Located here!</h3>

               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d255282.3586903348!2d36.6825805541912!3d-1.3028602819557469!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f1172d84d49a7%3A0xf7cf0254b297924c!2sNairobi!5e0!3m2!1sen!2ske!4v1698299243903!5m2!1sen!2ske" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
                <div class="form-group">
                    <label for="message">Message:</label>
                    <textarea class="form-control" id="message" rows="5" placeholder="Your Message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary button-spacing">Send</button>
            </form>
        </div>
    </div>
</section>



{% endblock %}

portfolio/Joan/templates/home.html
	{% extends 'layout.html' %}
{% load static %}
{% block body %}



<section class="container mt-5">
    <h2 class="text-center mb-4">About Me</h2>

    <div class="row">

        <div class="col-md-4 mb-4">
            <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>

        <div class="col-md-8">
            <p>My name is Ms Joan Chebet,I am outgoing, dedicated, and open-minded. I get across to people and adjust to changes with ease. I believe that a person should work on developing their professional skills and learning new things all the time.</p>
        </div>
    </div>



</section>



    <section class="container mt-5">
    <h2 class="text-center mb-4">Languages that i have knowledge about</h2>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3><strong>CSS</strong></h3>
            <p>CSS is an interpreted, high-level, general-purpose programming language. It's great for web development, data analysis, artificial intelligence, and more.</p>
        </div>
    </div>


    <div class="row mb-4">
        <div class="col-md-4">
            <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3><strong>HTML</strong></h3>
            <p>he HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It defines the meaning and structure of web content. It is often assisted by technologies such as Cascading Style Sheets and scripting languages such as JavaScript</p>
        </div>
    </div>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3><strong>Python</strong></h3>
            <p>Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured, object-oriented and functional programming.</p>
        </div>
    </div>



</section>



    <section class="container mt-5">
    <h2 class="text-center mb-4"> Services</h2>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Front-End Development</h3>
            <p>Creating the user interface and user experience by working with HTML, CSS, and JavaScript</p>
        </div>
    </div>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Back-End Development</h3>
            <p>Building the server-side components of a website or web application using server-side languages like PHP, Python, Ruby, Node.js, or Java</p>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Other Services</h3>
            <p>I also offer any other services that a client needs to get from me as per the client.Full-Stack Development: Combining front-end and back-end development to create complete web solutions</p>
        </div>
    </div>



</section>


    <section class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h3>Contact Info</h3>
            <ul class="list-unstyled">
                <li><strong>Phone:</strong> +254708242977</li>
                <li><strong>Email:</strong> chebetjoan110@gmail.com</li>
                <li><strong>Address:</strong> 811-20210 </li>
            </ul>
        </div>


        <div class="row mt-5">
            <div class="col-12">
                <h3>Am Located here!</h3>

               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d255282.3586903348!2d36.6825805541912!3d-1.3028602819557469!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f1172d84d49a7%3A0xf7cf0254b297924c!2sNairobi!5e0!3m2!1sen!2ske!4v1698299243903!5m2!1sen!2ske" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
        <div class="col-md-6">
            <h3>Send a Message</h3>
            <form>
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                </div>
                <div class="form-group">
                    <label for="message">Message:</label>
                    <textarea class="form-control" id="message" rows="5" placeholder="Your Message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary button-spacing">Send</button>
            </form>
        </div>
    </div>
</section>



{% endblock %}

portfolio/Joan/templates/languages.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
    <section class="container mt-5">
    <h2 class="text-center mb-4">Languages I Know</h2>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3><strong>HTML</strong></h3>
            <p>The HyperText Markup Language or HTML is the standard markup language for documents designed to be displayed in a web browser. It defines the meaning and structure of web content. It is often assisted by technologies such as Cascading Style Sheets and scripting languages such as JavaScript</p>
        </div>
    </div>


    <div class="row mb-4">
        <div class="col-md-4">
            <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3><strong>Python</strong></h3>
            <p> Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured, object-oriented and functional programming.</p>
        </div>
{% endblock %}

portfolio/Joan/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Joan</title>
</head>


<body>


<nav class="navbar bg-primary" data-bs-theme="dark">
    <a class="navbar-brand" href="#">Joan|portfolio</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link {% if nav == 'home' %} active-page {% endif %}" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if nav == 'about' %} active-page {% endif %}" href="{% url 'Joan:about' %}">About Me</a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if nav == 'languages' %} active-page {% endif %}" href="{% url 'Joan:languages' %}">Languages</a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if nav == 'services' %} active-page {% endif %}" href="{% url 'Joan:services' %}">Services</a>
            </li>
            <li class="nav-item">
                <a class="nav-link{% if nav == 'contacts' %} active-page {% endif %}" href="{% url 'Joan:contacts' %}">Contacts</a>
            </li>
        </ul>
    </div>
</nav>


<div id="aboutSlider" class="carousel slide mt-3" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#aboutSlider" data-slide-to="0" class="active"></li>
        <li data-target="#aboutSlider" data-slide-to="1"></li>
        <li data-target="#aboutSlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
            <div class="carousel-caption d-none d-md-block">
                <h5>My vision</h5>
                <p>Becoming the best Dev' in the society</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
            <div class="carousel-caption d-none d-md-block">
                <h5>Mission</h5>
                <p>Solving technical problems and bringing solution to the wolrd</p>
            </div>
        </div>
        <div class="carousel-item">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
            <div class="carousel-caption d-none d-md-block">
                <h5 class="passion">Fun</h5>
                <p class="passion">Coding!coding!coding!</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#aboutSlider" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#aboutSlider" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>




{% block body %} {% endblock %}
   <footer class="footer">
        <div class="row">

            <div class="col socials">
                <h3>Follow me on social media</h3>
                <div class="social-icons">
                    <a href="https://www.facebook.com/joan.chebet.16568"><i class="fa-brands fa-facebook"></i></a>
                    <a href="https://x.com/JoanChe79224678?s=09"><i class="fa-brands fa-x-twitter"></i></a>
                    <a href="https://www.tiktok.com/@joanchebet10?_t=8gizTSBLJxe&_r=1
"><i class="fa-brands fa-tiktok"></i></a>
                    <a href="https://instagram.com/joanche9?igshid=cHEzeThhNW50MHJ5"><i class="fa-brands fa-instagram"></i></a>
                    <a href="https://github.com/JOANCHEBET"><i class="fa-brands fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/joan-chebet-980b07218?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"><i class="fa-brands fa-linkedin"></i></a>
                </div>
            </div>

        </div>
        <hr>
        <p class="copyright">&copy; All rights reserved | Joan Chebet | <script>document.write(/\d{4}/.exec(Date())[0])</script></p>
    </footer>



<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

portfolio/Joan/templates/services.html
{% extends 'layout.html' %}
{% load static %}
{% block body %}
     <section class="container mt-5">
    <h2 class="text-center mb-4">Services</h2>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Front-End Development</h3>
            <p>Creating the user interface and user experience by working with HTML, CSS, and JavaScript</p>
        </div>
    </div>


    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Back-End Development</h3>
            <p> Building the server-side components of a website or web application using server-side languages like PHP, Python, Ruby, Node.js, or Java.</p>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-md-4">
             <img src="{% static 'images/Passport.jpg' %}" alt="" width="400" height="250" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h3>Other Services</h3>
            <p>Full-Stack Development: Combining front-end and back-end development to create complete web solutions.</p>
        </div>
    </div>



</section>

{% endblock %}